# Generated by Django 4.2.7 on 2023-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task'),
        ('task', '0002_rename_date_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
